version: '2.1'
services:
  photos:
    # image: bhcr.io/balenablocks/photo-gallery-armv7hf
    build: ./photo-gallery
    privileged: true
    restart: always
    network_mode: host
    environment:
      UDEV: "on"
  kiosk:
    image: bhcr.io/balenablocks/browser-armv7hf
    privileged: true
    network_mode: host
    environment: 
      LAUNCH_URL: "http://localhost:8888/"
      KIOSK: '1'
