version: '2.1'
services:
  photos:
    # image: bhcr.io/balenablocks/photo-gallery-armv7hf
    build: ./photo-gallery
    privileged: true
    restart: always
    ports:
      - 8888
  kiosk:
    image: bhcr.io/balenablocks/browser-armv7hf
    privileged: true
    environment: 
      LAUNCH_URL: "http://photos:8888/"
      KIOSK: '1'
    ports:
      - 5011
      - 35173
